package com.imageservice.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import java.util.List;

@Builder
@Data
@AllArgsConstructor
public class PostResponse {
    // TODO uuid? generated by the db

    // TODO Knock down to one class instead of PostResponse and Image
    private Long imageId;

//    private Image image;
//    private String image;
//
//    private String imageUrl;

    private String label;

    private List<String> detectedObjects;

}
