package com.imageservice.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import java.util.List;

@Builder
@Data
@AllArgsConstructor
public class PostResponse {
    // TODO uuid? generated by the db
    private String imageId;

    private ImageFile image;

    // TODO generate label if not provided
    private String label;
}
