package com.imageservice.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Builder
@Data
@AllArgsConstructor
public class PostResponse {
    // TODO uuid? generated by the db
    private String imageId;

    private Image image;

}
